### ISSUE TITLE
Export-NessusScan PDF and HTML reports are empty

### ISSUE THREAD

**Issue by mg07647** [tenable/Posh-Nessus#10]
When the format is CSV it generates correct output, but if the format is PDF or HTML, a report is generated but it only has the cover page, an empty table of contents, and no content.

**Comment by darkoperator** [comment]
Are you specifying the chapters you want for PDF and HTML?

**Comment by mg07647** [comment]
You're correct - I forgot to specify the chapters. Closing as invalid.

BTW thanks for the quick response and the hard work!

**Comment by Poko1970** [comment]
How d

**Comment by Poko1970** [comment]
How do you specify the chapters? And where do you find them?
I have the same problem if I enter: Export-NessusScan 0 14 "csv" >E:\DaveScripts\nessus.csv

CSV works fine (although FAR too verbose) but PDF and HTML are empty. All I really want is a summary like you see on the nessus dashboard

**Comment by darkoperator** [comment]
use the parameter Chapters https://github.com/tenable/Posh-Nessus/blob/master/Scan.ps1#L685 <https://github.com/tenable/Posh-Nessus/blob/master/Scan.ps1#L685> and then specify in the parameter OutFile the file to save the report to

**Comment by Poko1970** [comment]
Ha! Thank you SO much! Quite new to this lark, and your script is really good! It's doing stuff that I didn't know was possible :)
