### ISSUE TITLE
New scan doesn't add a custom policy

### ISSUE THREAD

**Issue by leunammejii** [tenable/Posh-Nessus#11]
Adding the `policy_id` key and value to the `$settings` in the `New-NessusScan` function allows one to apply a custom policy. I added the following on `line 1384 in Scan.ps1`:
```powershell
if ($PolicyId) {$settings.Add('policy_id',$PolicyId)}

**Comment by darkoperator** [comment]
Thank you for reporting this. Pushed a new version with the fix.
