### ISSUE TITLE
Export-NessusScan only pulls the latest history item/report

### ISSUE THREAD

**Issue by masters274** [tenable/Posh-Nessus#13]
In the `foreach($Connection in $ToProcess)`, the path is hard coded as `$path =  "/scans/$($ScanId)/export"`. If you add the following, after this hardcoded path, it would allow you to download a specified history report instead of just the latest report.

`if($HistoryID)
{
    $path = "/scans/$($ScanId)/export?history_id=$($HistoryId)"
}`

Thanks for such great contributions!

**Comment by leunammejii** [comment]
I sumbitted a pull request to solve this issue. I also added an `else` statement just in case a user doesn't specify the history ID since it is not a mandatory parameter.

**Comment by darkoperator** [comment]
pull request merged, thanks :
