### ISSUE TITLE
New-NessusScan with 'advanced' and 'custom' policies

### ISSUE THREAD

**Issue by jmmcatee** [tenable/Posh-Nessus#6]
We build our own policies to enable specific plugins and mark these as "advanced" scans to allow us to audit the plugins, since "custom" scans do not show the plugins in the Nessus web interface. In order to get a scan to be created based on those policies we had to create a custom version of the New-NessusScan command, which does not use the UUID of the policy (advanced), but instead uses the UUID of "custom" scan and then provides the appropriate PolicyID for the scan we picked. This seems to be how the web interface handles this. 

I'm curious if anyone has an idea how this could be handled better than a second Cmdlet or if I'm totally missing something on how this should/is supposed to work.

**Comment by darkoperator** [comment]
You should be able to specify a PolicyUUID of a policy you created from a template, a PolicyID or a Policy Name in the the next update planned using new-nessusscan. You can test it by checking out the following branch https://github.com/tenable/Posh-Nessus/tree/ScanScheduling <https://github.com/tenable/Posh-Nessus/tree/ScanScheduling>

**Comment by darkoperator** [comment]
Typically the workflow is:

 Create Policy from Template -> set parameters on policy -> create scan based on policy

What would your specific steps be?
